export {
	type BasePageOptions,
	BasePageV2,
	type ExtractBaseUrlType,
	type ExtractFullUrlType,
	type ExtractUrlPathType,
} from "./basePage";
export { test } from "./fixture/base.fixtures";
export { type LogEntry, type LogLevel, PlaywrightReportLogger } from "./helpers/playwrightReportLogger";
export type {
	AltTextDefinition,
	DataCyDefinition,
	FilterDefinition,
	FilterLocatorReference,
	FrameLocatorDefinition,
	IdDefinition,
	IndexSelector,
	LabelDefinition,
	LocatorDefinition,
	LocatorOverrides,
	LocatorSchemaPathError,
	LocatorSchemaPathErrors,
	LocatorSchemaPathFormat,
	LocatorStep,
	LocatorStepOverride,
	LocatorStrategyDefinition,
	LocatorUpdate,
	PathIndexMap,
	PlaceholderDefinition,
	PlaywrightFilterDefinition,
	ResolvedFilterDefinition,
	RoleDefinition,
	TestIdDefinition,
	TextDefinition,
	TitleDefinition,
} from "./locators";
export {
	type AddAccessor,
	createRegistryWithAccessors,
	type GetLocatorAccessor,
	type GetLocatorSchemaAccessor,
	type GetNestedLocatorAccessor,
	LocatorQueryBuilder,
	LocatorRegistrationBuilder,
	type LocatorRegistry,
	LocatorRegistryInternal,
} from "./locators";
